// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'npx tsx prisma/seed/main.ts',
  },
  datasource: {
    url: env('DIRECT_URL'),
    // Type assertion silences TS(2353) while Prisma CLI resolves the underlying keyword 'url' to 'directUrl' for compatibility with Prisma Client.
    directUrl: env('DIRECT_URL'),
  } as any,
});